# Generated by Django 3.1.1 on 2020-11-19 21:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado_Alcoholico',
            fields=[
                ('grado', models.FloatField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Grado Alcohol')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Marca del Licor')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20, verbose_name='Material')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Pais de Origen')),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('sabor', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Sabor del Licor')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.FloatField(verbose_name='Tamaño del licor')),
                ('unidad', models.CharField(choices=[('L', 'Litros'), ('mL', 'Mililitros')], default='L', max_length=2, unique=True, verbose_name='Unidad de Medida')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Tipo de Licor')),
            ],
        ),
        migrations.CreateModel(
            name='Licor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Licor')),
                ('id_licor', models.CharField(max_length=20, unique=True)),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.tamano')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.grado_alcoholico')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.marca')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.material')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.pais')),
                ('sabor', models.ManyToManyField(to='Licores.Sabor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.tipo')),
            ],
        ),
    ]
