# Generated by Django 3.1.1 on 2020-11-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licor',
            options={'verbose_name': 'Licor', 'verbose_name_plural': 'Licores'},
        ),
    ]
