# Generated by Django 3.1.1 on 2020-11-24 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0002_auto_20201119_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licor',
            name='Tamano',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='id',
        ),
        migrations.AddField(
            model_name='licor',
            name='tamano',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tamaño del licor'),
        ),
        migrations.AddField(
            model_name='licor',
            name='unidad',
            field=models.CharField(choices=[('L', 'Litros'), ('mL', 'Mililitros')], default='L', max_length=2, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='grado',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Grado Alcohol'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='id_licor',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='licor',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca del Licor'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='material',
            field=models.CharField(max_length=20, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='pais',
            field=models.CharField(max_length=20, verbose_name='Pais de Origen'),
        ),
        migrations.RemoveField(
            model_name='licor',
            name='sabor',
        ),
        migrations.AddField(
            model_name='licor',
            name='sabor',
            field=models.CharField(default='Original', max_length=20, verbose_name='Sabor del Licor'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo de Licor'),
        ),
        migrations.DeleteModel(
            name='Grado_Alcoholico',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Sabor',
        ),
        migrations.DeleteModel(
            name='Tamano',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
