# Generated by Django 3.1.1 on 2020-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0003_auto_20201124_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licor',
            name='sabor',
            field=models.CharField(max_length=20, verbose_name='Sabor del Licor'),
        ),
    ]
