# Generated by Django 3.1.1 on 2020-11-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0004_auto_20201124_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='licor',
            name='imagen',
            field=models.ImageField(default='Licores/img/Default.jpg', upload_to='Licores/img', verbose_name='Imagen del Licor'),
        ),
    ]
