# Generated by Django 3.1.1 on 2020-11-24 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0006_auto_20201124_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licor',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='material',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='licor',
            name='unidad',
        ),
        migrations.AddField(
            model_name='licor',
            name='descripcion',
            field=models.TextField(default='Descripcion del Producto', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='licor',
            name='nombre_provedor',
            field=models.CharField(default='provedor', max_length=30, verbose_name='Nombre del Proovedor'),
        ),
        migrations.AddField(
            model_name='licor',
            name='ubicacion',
            field=models.CharField(default='Caracas', max_length=50, verbose_name='Ubicacion del Proovedor'),
        ),
        migrations.AddField(
            model_name='licor',
            name='valoracion',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Valoracion'),
        ),
    ]
