# Generated by Django 3.1.1 on 2020-11-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0008_auto_20201124_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licor',
            options={'ordering': ['id'], 'verbose_name': 'Licor', 'verbose_name_plural': 'Licores'},
        ),
        migrations.RemoveField(
            model_name='licor',
            name='id_licor',
        ),
        migrations.AddField(
            model_name='licor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licor',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion del Producto'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='nombre_provedor',
            field=models.CharField(max_length=30, verbose_name='Nombre del Proovedor'),
        ),
    ]
