# Generated by Django 3.1.1 on 2020-11-24 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0009_auto_20201124_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='licor',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
