# Generated by Django 3.1.1 on 2020-11-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0010_licor_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licor',
            name='imagen',
            field=models.ImageField(default='img/None.png', upload_to='core/Licores/static/Licores/img', verbose_name='Imagen del Licor'),
        ),
    ]
