# Generated by Django 3.1.1 on 2020-11-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0011_auto_20201124_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='img/None.png', upload_to='core/Licores/static/Licores/img', verbose_name='Imagen del Licor')),
            ],
        ),
        migrations.AlterField(
            model_name='licor',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.imagen'),
        ),
    ]
