# Generated by Django 3.1.1 on 2020-11-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0012_auto_20201124_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licor',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licores.imagen', verbose_name='Imagen del Licor'),
        ),
    ]
