# Generated by Django 3.1.1 on 2020-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licores', '0013_auto_20201124_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licor',
            name='imagen',
            field=models.ImageField(default='img/None.png', upload_to='core/Licores/static/Licores/img', verbose_name='Imagen del Licor'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
